### ISSUE TITLE
Dividing Tasks Sprint #1

### ISSUE THREAD

**Issue by danielanthonyr** [davidberard2/SOEN341GROUPC#1]
Tasks for sprint 1

- [x]  Setup Database (Firebase)
**Evan , Loic , Karen**

- [x] Setup Android side
**Kayne, David, Daniel, Alex , Chen, Evan**

- [x] Documentation

**Comment by kwreen** [comment]
How about we keep the 'Documentation' part with 'Minutes' for now?
