### ISSUE TITLE
Image uploading

### ISSUE THREAD

**Issue by Alex-Hayeur** [davidberard2/SOEN341GROUPC#26]
Allows users to upload pictures of the items they are selling to the database, which appear on the item's listing page.

- [x] Create button
- [x] Create onClick function uploading picture from gallery
- [x] Upload the picture to FirebaseStorage
- [x] Update FirebaseDatabase with the new picture link

Link to relevant User Story  [here](https://github.com/davidberard2/SOEN341GROUPC/wiki/User-Stories-Logs#Sprint-3)

**Comment by Alex-Hayeur** [comment]
Link to corresponding Sprint Goal on wiki [here](https://github.com/davidberard2/SOEN341GROUPC/wiki/Sprint-Logs#sprint-3)

**Comment by davidberard2** [comment]
This issue is close for profil purposes. I'll need to reuse the methods for items.
