### ISSUE TITLE
Features to develop this sprint

### ISSUE THREAD

**Issue by davidberard2** [davidberard2/SOEN341GROUPC#4]
Back end:
- [x] Database/Account management
- [x] Dummy data for listing
- [x] Find solution of relation between account and database

Remember
- Good commenting habits

Create database need chanel

Those 4 major steps will set up the base of our app, later feature can easily be added. It also provide a good picture of the possible future of the app.

**Comment by cxt714** [comment]
![team logo](https://user-images.githubusercontent.com/31772703/30776385-00970768-a0d8-11e7-8710-ad7e744ee53b.png)
My name is Chen :)

**Comment by davidberard2** [comment]
This issue has been resolved.
