### ISSUE TITLE
Icon image 

### ISSUE THREAD

**Issue by kkhh001** [davidberard2/SOEN341GROUPC#41]
By creating an image for the app, it will allow people to recognize the app on Google Play Store. 
- [x] Create Logo 
- [x] Upload logo to GitHub
- [x] Implement app icon image 

Link to relevant User Story

**Comment by cxt714** [comment]
change default pics

**Comment by davidberard2** [comment]
This as been fixed as part of issue #26. It still has place for improvement since the icon is using direct referencing instead of mipmaps.
