### ISSUE TITLE
Enhance profile page

### ISSUE THREAD

**Issue by davidberard2** [davidberard2/SOEN341GROUPC#56]
- [x] Scroll implementation
- [x] Name implemented as First Name and Last Name
- [x] Use editText instead of textInput for enabling and disabling
- [x] Save button and modify (pen) button
- [x] Add log out button when logged in

The set up for when logged out has been implemented last sprint by Alex

PLEASE ADD CHECKMARK AS TASK FOR STORY POINTS IMPLEMENTATION.

**Comment by kwreen** [comment]
@davidberard2 I don't think the log out button is necessary on the profile if the settings option is kept in the menu on top.
