### ISSUE TITLE
Architectural Diagram 

### ISSUE THREAD

**Issue by kkhh001** [davidberard2/SOEN341GROUPC#64]
The architectural diagram follows the MVP format:

- [x] Discuss components and connectors with teammates 
- [x] Create architectural diagram
- [x] Review architectural diagram with team members

**Comment by kkhh001** [comment]
![ad 1](https://user-images.githubusercontent.com/22185426/32638947-896b6904-c58f-11e7-98a7-9a9a34097ad8.jpg)

**Comment by LHuss** [comment]
I don't think Android Studio and Firebase should be in the same container, but apart from that this looks right.

**Comment by danielanthonyr** [comment]
I agree with @LHuss , although android studio has built in functionality to work with firebase, it should still be treated as its own entity (firebase) that communicates with Android studio through interfaces etc etc

**Comment by EvanMateo7** [comment]
The container of the nodes, "Java" should probably include XML as this is what we use to create the views

**Comment by danielanthonyr** [comment]
Also, Listings should be part of the Models as we are creating objects from it, Profile and login java files should be in controllers (since it is doing logic) and all xml files should be in views, Please review the MVP pattern for android.

**Comment by cxt714** [comment]
I suggest Firebase should be removed from Android Studio, and then add  arrows between then to show that they are interrelated， agree put " xml" in views.

**Comment by Alex-Hayeur** [comment]
Aside from what people mentioned above, would it be possible to make it more clear that our fragment files are views, while all the non-fragment java files are controllers? Just to make the "..." clearer.

**Comment by kkhh001** [comment]
Will take all of your suggestions into considerations and make the required changes. Thanks for all the great feedback!

**Comment by kwreen** [comment]
We should also have the Activities included with the Fragments, and I'm thinking that there should be a direct arrow going from the Model to the View, since if the Model gets updated, it'll directly translate into our View.

**Comment by kkhh001** [comment]
@kwreen Actually, by following the MVP architecture, there should not be any arrows in between those two layers. In fact, the View is completely passive and data is always delivered to the View by the Presenter (the middle man).
![unknown](https://user-images.githubusercontent.com/22185426/32812726-82781b54-c974-11e7-8c9f-0b4d7f843980.png)

**Comment by EvanMateo7** [comment]
I agree with @kkhh001, we have an MVP architecture. Although the View does get updated when the Model changes, it does this indirectly through the Presenter which is where **all** the business logic should be. (I hope this is the case)

**Comment by kkhh001** [comment]
![mvp](https://user-images.githubusercontent.com/22185426/32869322-5569184a-ca44-11e7-938d-50cc56902be3.png)

Here is the modified version of the architectural diagram, please let me know if something has to be changed. Thanks!

**Comment by kwreen** [comment]
If anyone was curious, this is the response I got from the teacher:
![image](https://user-images.githubusercontent.com/23409994/32904720-08187374-cac6-11e7-8e2e-45c077c2258f.png)

The question I asked was the following: if there is no direct communication between the Model and the View, does it make an architecture not an MVC architecture? Does it make it an MVP architecture then?

@kkhh001 I think you meant to write Business logic instead of UI logic inside the Presenter. I also think if it's possible that the lines should mostly remain straight to make it look cleaner (e.g. from Firebase to Model, Model to Presenter, Presenter to User). I also would keep the word Model and View in the singular form because they are concepts.

**Comment by kkhh001** [comment]
Thanks for emailing the teacher @kwreen! For now, I will not put an arrow from the View to the Model since i don't fully understand why the MVP architecture would need one. From my perspective, it defeats the Presenter's role, which is to act as a middle man. However, I will further discuss this issue with Giancarlo (TA) / Emad ASAP. As for your other comments, I will definitely do these modifications. Thanks for pointing them out 👍

**Comment by kkhh001** [comment]
![f mvp](https://user-images.githubusercontent.com/22185426/32926070-25463916-cb13-11e7-9306-4c6a4ec48cf7.png)
